force-app/main/default/objects/BatchLot__c/BatchLot__c.object-meta.xml
<CustomObject>
    <label>Batch Lot</label>
    <nameField>
        <label>Batch Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Lots</pluralLabel>
    <searchStatus>Inactive</searchStatus>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchLot__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Batch Lots</relationshipLabel>
    <relationshipName>BatchLots</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GRN__c/GRN__c.object-meta.xml
<CustomObject>
    <label>GRN</label>
    <pluralLabel>GRNs</pluralLabel>
    <nameField>
        <displayFormat>GRN-{0000}</displayFormat>
        <label>GRN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <searchStatus>Active</searchStatus>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>PrimaryOrder__c</fullName>
        <label>Primary Order</label>
        <referenceTo>PrimaryOrder__c</referenceTo>
        <relationshipLabel>GRNs</relationshipLabel>
        <relationshipName>GRNs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ScannerSessionId__c</fullName>
        <label>Scanner Session ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VarianceJSON__c</fullName>
        <label>Variance JSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <validationRules>
        <fullName>Posted_DamagedQty_Check</fullName>
        <active>true</active>
        <description>Posted cannot be true if any GRNLine has DamagedQty > AcceptedQty</description>
        <errorConditionFormula>Posted__c = true</errorConditionFormula>
        <errorDisplayField>Posted__c</errorDisplayField>
        <errorMessage>Cannot post GRN with damaged quantity exceeding accepted quantity</errorMessage>
    </validationRules>
</CustomObject>

force-app/main/default/objects/GRN__c/fields/PrimaryOrder__c.field-meta.xml
<CustomField>
    <fullName>PrimaryOrder__c</fullName>
    <label>PrimaryOrder</label>
    <referenceTo>PrimaryOrder__c</referenceTo>
    <relationshipLabel>Related Records</relationshipLabel>
    <relationshipName>Related_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GRNLine__c/GRNLine__c.object-meta.xml
<CustomObject>
    <label>GRN Line</label>
    <masterDetail>
        <masterLabel>GRN__c</masterLabel>
        <relationshipLabel>GRN Lines</relationshipLabel>
        <relationshipName>GRN_Lines</relationshipName>
    </masterDetail>
    <pluralLabel>GRN Lines</pluralLabel>
    <searchStatus>Inactive</searchStatus>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GRNLine__c/fields/AcceptedQty__c.field-meta.xml
<CustomField>
    <fullName>AcceptedQty__c</fullName>
    <label>AcceptedQty</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GRNLine__c/fields/ReceivedQty__c.field-meta.xml
<CustomField>
    <fullName>ReceivedQty__c</fullName>
    <label>ReceivedQty</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PrimaryOrder__c/PrimaryOrder__c.object-meta.xml
<CustomObject>
    <label>Primary Order</label>
    <nameField>
        <label>Primary Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Orders</pluralLabel>
    <searchStatus>Inactive</searchStatus>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GRNLineTriggerHandlerTest.cls
/**
 * @description Test class for GRNLineTriggerHandler
 */
@isTest
private class GRNLineTriggerHandlerTest {
    
    @testSetup
    static void setup() {
        Account distributor = new Account(Name = 'Test Distributor');
        insert distributor;
        
        Product2 product = new Product2(Name = 'Test Product', IsActive = true);
        insert product;
        
        PrimaryOrder__c primaryOrder = new PrimaryOrder__c(Distributor__c = distributor.Id);
        insert primaryOrder;
        
        GRN__c grn = new GRN__c(PrimaryOrder__c = primaryOrder.Id);
        insert grn;
    }
    
    @isTest
    static void testCreateBatchLot() {
        GRN__c grn = [SELECT Id FROM GRN__c LIMIT 1];
        Product2 product = [SELECT Id FROM Product2 LIMIT 1];
        
        Test.startTest();
        GRNLine__c line = new GRNLine__c(
            GRN__c = grn.Id,
            Product__c = product.Id,
            ReceivedQty__c = 100,
            AcceptedQty__c = 100
        );
        insert line;
        Test.stopTest();
        
        List<BatchLot__c> lots = [SELECT Id FROM BatchLot__c];
        System.assert(lots.size() > 0);
    }
}